# Generated by Django 4.2 on 2025-06-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان شغلی')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('short_bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='بیوگرافی کوتاه')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='تصویر پروفایل')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='تصویر کاور')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('website', models.URLField(blank=True, null=True, verbose_name='وب\u200cسایت')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='سال\u200cهای تجربه')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دانشجویان')),
                ('courses_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دوره\u200cها')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='مهارت\u200cها (هر مهارت در یک خط)')),
                ('specializations', models.TextField(blank=True, null=True, verbose_name='تخصص\u200cها (هر تخصص در یک خط)')),
                ('certificates', models.TextField(blank=True, null=True, verbose_name='گواهینامه\u200cها')),
                ('awards', models.TextField(blank=True, null=True, verbose_name='افتخارات و جوایز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پروفایل استاد',
                'verbose_name_plural': 'پروفایل\u200cهای اساتید',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
