# Generated by Django 5.2.3 on 2025-06-30 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان صفحه تماس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='description',
            field=models.TextField(default='', verbose_name='توضیحات صفحه تماس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره موبایل'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='fax',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='فکس'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='working_hours',
            field=models.TextField(blank=True, null=True, verbose_name='ساعات کاری'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='تلگرام'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='واتساپ'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='لینکدین'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='توییتر'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_form_title',
            field=models.CharField(default='فرم تماس با ما', max_length=200, verbose_name='عنوان فرم تماس'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='contact_form_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات فرم تماس'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('read', 'خوانده شده'), ('replied', 'پاسخ داده شده'), ('closed', 'بسته')], default='new', max_length=10, verbose_name='وضعیت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام‌های تماس',
                'ordering': ['-created_at'],
            },
        ),
    ]
