# Generated by Django 4.2 on 2025-06-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='نام آیکون Lucide', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('hero_title', 'عنوان اصلی'), ('hero_subtitle', 'زیرعنوان اصلی'), ('hero_description', 'توضیحات اصلی'), ('hero_button_text', 'متن دکمه اصلی'), ('hero_button_url', 'لینک دکمه اصلی'), ('features_title', 'عنوان ویژگی\u200cها'), ('features_subtitle', 'زیرعنوان ویژگی\u200cها'), ('instructor_title', 'عنوان بخش استاد'), ('instructor_subtitle', 'زیرعنوان بخش استاد'), ('instructor_description', 'توضیحات استاد'), ('newsletter_title', 'عنوان خبرنامه'), ('newsletter_subtitle', 'زیرعنوان خبرنامه')], max_length=50, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button_url', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_content/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
